- name: Checkout code
  uses: actions/checkout@v2
- name: Install AWS CLI
  run: |
     sudo apt-get update
     sudo apt-get install -y awscli
- name: Create AWS credentials directory
  run: mkdir -p ~/.aws
        
- name: Configure AWS credentials
  run: |
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id=${AWS_ACCESS_KEY_ID}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}" >> ~/.aws/credentials
          
- name: Set up Terraform
  uses: hashicorp/setup-terraform@v1
  with:
    terraform_version: 1.5
