name: Terraform Workflow
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - feature
jobs:
  terraform-master:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master' || github.event_name == 'workflow_dispatch'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
      - name: Create AWS credentials directory
        run: mkdir -p ~/.aws
        
      - name: Configure AWS credentials
        run: |
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id=${AWS_ACCESS_KEY_ID}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}" >> ~/.aws/credentials
          
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5
     
      - name: Install TFLint
        run: |
            wget https://github.com/terraform-linters/tflint/releases/download/v0.32.0/tflint_linux_amd64.zip
            unzip tflint_linux_amd64.zip
            sudo mv tflint /usr/local/bin/
  
      - name: Run TFLint
        run: tflint
      
      - name: Format Terraform Code
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init

      - name: Validate Terraform Code
        run: terraform validate

      - name: terraform plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
        
      - name: Terraform destroy
        if: github.event_name == 'workflow_dispatch'
        run: terraform destroy --auto-approve

  terraform-feature:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/feature'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
      - name: Create AWS credentials directory
        run: mkdir -p ~/.aws
        
      - name: Configure AWS credentials
        run: |
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id=${AWS_ACCESS_KEY_ID}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}" >> ~/.aws/credentials
          
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5

      - name: Install TFLint
        run: |
            wget https://github.com/terraform-linters/tflint/releases/download/v0.32.0/tflint_linux_amd64.zip
            unzip tflint_linux_amd64.zip
            sudo mv tflint /usr/local/bin/
  
      - name: Run TFLint
        run: tflint
      
      - name: Format Terraform Code
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init

      - name: Validate Terraform Code
        run: terraform validate

      - name: terraform plan
        run: terraform plan

        
